[workspace]

members = [
    "10_min_walk",
    "british_vs_slovakian_post_codes",
    "connect_four",
    "pangram",
    "count_chars"
, "pokemon_battle", "add_up_array", "dynamic_box", "tcp_typestate_pattern", "trait_challenge_1", "head", "design_patterns/singleton"]
